routes/web.php
<?php

use App\Http\Livewire\Access\RegLog;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Panel\Users\Users;
use App\Http\Livewire\Panel\PanelControl;
use App\Http\Controllers\VerifyUserController;
use App\Http\Livewire\Panel\Users\UserRegiEdit;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/', PanelControl::class)->name('user');

Route::get('reg-log', RegLog::class)->name('login');
Route::post('reg-log', RegLog::class)->name('logout');

Route::get('account/verify/{token}', VerifyUserController::class)->name('verify');

Route::group(['middleware' => ['auth', 'user-veri-email'], 'prefix' => 'panel'], function(){

    Route::group(['prefix' => '', 'as' => 'panel.'], function(){

        // Panel
        Route::get('', PanelControl::class)->name('index');

    });

    Route::group(['prefix' => 'usuarios', 'as' => 'usuarios.'], function(){

        Route::get('', Users::class)->name('index');
        // Route::get('crear', UserForm::class)->name('create');
        // Route::get('{user}', UserShow::class)->name('show');

        // Route::get('{user}/borrar', Users::class)->name('delete');
        // Route::get('{user}/perfil', UserProfile::class)->name('details');
        // Route::view('/perfil/user', 'partials.panel.perfil')->name('profile');
    });

    Route::group(['prefix' => 'usuario', 'as' => 'usuario.'], function(){

        Route::get('crear', UserRegiEdit::class)->name('create');
        Route::get('{user}/editar', UserRegiEdit::class)->name('editar');

        // Route::get('{user}/borrar', Users::class)->name('delete');
        // Route::get('{user}/perfil', UserProfile::class)->name('details');
        // Route::view('/perfil/user', 'partials.panel.perfil')->name('profile');
    });
});

app/Http/Livewire/Panel/PanelControl.php
<?php

namespace App\Http\Livewire\Panel;

use Livewire\Component;

class PanelControl extends Component
{
    public function render()
    {
        return view('livewire.panel.panel-control')
        ->layout('layouts.app-panel', ['title' => 'Control Panel']);
    }
}

app/Http/Livewire/Panel/Users/UserPass.php
<?php

namespace App\Http\Livewire\Panel\Users;

use App\Models\User;
use Livewire\Component;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserPass extends Component
{
    // public User $user;
    public $user, $current_password, $new_password, $confirm_password;


    // public function mount(User $user)
    // {
    //     $this->user = $user;    
    // }

    public function render()
    {
        return view('livewire.panel.users.user-pass')
        ->layout('layouts.app-panel', ['title' => 'Usuario contraseña']);
    }

    public function changepass()
    {
        $this->validate([
            'current_password'  => [
                'required',
                function ($value, $error)
                {
                    if (!Hash::check($value, User::find($this->user->id)->password)) {
                        return $error(__('the current password is incorrect'));
                    }
                },
            ],
            'new_password'     => 'required|min:3',
            'confirm_password' => 'same:new_password',
        
        ],[
            'current_password.required'  => __('enter your current password.'),
            'new_password.required'      => __('enter your new password.'),
            'confirm_password.same'      => __('confirme new password, must be equals to the new password'),
        ]);

        $query = User::find(auth('web')->id())->update([
            'password' => bcrypt($this->new_password)
        ]);

        if ($query) {
            session()->flash('msg', __('contra cambiada correctamente.'));
            $this->redirectRoute('usuarios.index');
            $this->current_password = $this->new_password = $this->confirm_password = null;
        } else {
            session()->flash('msg', __('error con las contraseñas.'));
        }
        
        // dd('los passworeds');
    }

}

app/Http/Livewire/Panel/Users/UserRegiEdit.php
<?php

namespace App\Http\Livewire\Panel\Users;

use App\Models\Img;
use App\Models\User;
use App\Traits\hasUpload;
use Livewire\Component;
use Livewire\WithFileUploads;
use Illuminate\Validation\Rule;

class UserRegiEdit extends Component
{
    use WithFileUploads, hasUpload;

    public User $user;
    public $photo;
    public $password;

    protected function rules(){
        return [
            'user.name' => 'required|min:3|string',
            'user.username' => 'nullable|min:3',
            'user.slug' => [
                'nullable',
                'alpha_dash',
                Rule::unique('users', 'slug')->ignore($this->user)
            ],
            'user.email' => [
                'required',
                Rule::unique('users', 'email')->ignore($this->user)
            ],
            'user.bio' => 'nullable|min:3',
            'photo' => [
                $this->user->photo ? '' : '',
                'nullable',
                'image',
                'max:2048',
                // Rule::exists('users', 'photo')->ignore($this->user)
            ],
            // 'photo' => 'nullable|exists:users,photo,'.$this->user->photo,
            'password' => [
                'required',
                'min:3',
                Rule::unique('users', 'password')->ignore($this->user->id)
            ]
        ];
    }

    public function mount(User $user, Img $photo){
        $this->user = $user;
        $this->photo = $photo;
        $this->password = $user->password;
    }

    public function updated($propertyName){
        $this->validateOnly($propertyName);
    }

    public function regedit(){
        $this->validate();

        $this->user->password = bcrypt($this->password);
        $this->user->save();

        if ($this->photo) {
            $this->photo = $this->uploadImage($this->user);
        }

        session()->flash('msg', __('user successfully created or edited.'));
        $this->redirectRoute('usuarios.index');
    }

    public function render(){
        return view('livewire.panel.users.user-regi-edit')
            ->layout('layouts.app-panel', ['title' => 'Crear Usuario']);
    }
}

app/Http/Livewire/Panel/Users/Users.php
<?php

namespace App\Http\Livewire\Panel\Users;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Users extends Component
{
    use WithPagination;

    public $search = '';

    public function render()
    {
        return view('livewire.panel.users.users', [
            'users' => User::where('name', 'like', "%{$this->search}%")->latest()->get()
        ])
        ->layout('layouts.app-panel', ['title' => 'Panel Usuarios']);
    }
}

resources/views/inc/panel/img.blade.php
<label  class="relative flex items-center justify-center w-auto p-3 mx-auto my-5 border border-dashed rounded-tl-lg rounded-br-lg shadow h-96 shadow-inherit bg-slate-700">
    {{-- $photo instanceof Livewire\TemporaryUploadedFile --}}
    @if ()
        
    @else
        
    @endif

    {{-- @if($photo instanceof Livewire\TemporaryUploadedFile)
        <span wire:click="$set('photo')" class="absolute p-3 bg-orange-600 rounded-tl-lg rounded-br-lg shadow cursor-pointer bottom-2 right-2 shadow-inherit">
            {{Str::ucfirst(__('change photo'))}}
        </span>
        <img class="w-full h-full bg-cover " src="{{ $photo->temporaryUrl() }}" alt="">
    @endif --}}
        {{-- <span class="p-3 bg-orange-600 rounded-tl-lg rounded-br-lg shadow cursor-pointer shadow-inherit">
            {{Str::ucfirst(__('select profile picture'))}}
        </span>
        <input wire:model="photo" class="my-5 text-xl text-white border border-gray-300 cursor-pointer sr-only bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" type="file">
        @error("photo")
        <span class="absolute p-2 text-xl text-white top-2 bg-slate-950">{{ $message }}</span>
        @enderror --}}
 
   {{-- <img src="{{ Storage::url($user->image()->first()->url) }}" alt=""  class="h-full bg-cover ">
        <span class="absolute p-3 bg-orange-600 rounded-tl-lg rounded-br-lg shadow cursor-pointer bottom-2 right-2 shadow-inherit">
            {{Str::ucfirst(__('change photo'))}}
        </span> --}}
</label>

resources/views/inc/panel/nav-movil.blade.php
<!-- Submenú Movil -->
<div x-data="{ open: false }">
    <!-- Button -->
    <button @click="open = ! open" class="absolute bottom-7 right-7 lg:hidden ">
        <svg class="w-7 h-7 text-white shadow shadow-slate-900 bg-black" fill="none" stroke="currentColor" stroke-width="1.5" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" stroke-linecap="round" stroke-linejoin="round">
            </path>
        </svg>
    </button>
    <div @click.outside="open = false" class="absolute top-16 bottom-7 left-0 flex flex-col w-4/5 h-screen text-white bg-black divide-y divide-red-300 shadow shadow-slate-900 lg:hidden" x-show="open">
        <a class="px-5 py-3 hover:bg-slate-700" href="#">
            About Us
        </a>
        <a class="px-5 py-3 hover:bg-slate-700" href="#">
            Contact Us
        </a>
        <a class="px-5 py-3 hover:bg-slate-700" href="#">
            Privacy Policy
        </a>
        <div class="">
            <button class="relative w-full px-5 py-2 text-white bg-green-600 peer hover:bg-green-700">
                Submenú
            </button>
            <!-- the menu here -->
            <div class="absolute flex-col hidden w-2/3 mt-1 peer-hover:flex hover:flex bg-slate-900 drop-shadow-lg">
                <a class="px-5 py-3 hover:bg-slate-700" href="#">
                    About Us
                </a>
                <a class="px-5 py-3 hover:bg-slate-700" href="#">
                    Contact Us
                </a>
                <a class="px-5 py-3 hover:bg-slate-700" href="#">
                    Privacy Policy
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Submenú Movil -->

resources/views/inc/panel/nav-panel.blade.php
<nav class="bg-green-800 lg:flex flex-col p-2 rounded-tl-lg gap-1 rounded-br-lg shadow shadow-black ">
    @include('inc.panel.nav-perfil')
    <a class="shadow shadow-inherit bg-slate-950 hover:bg-stone-700 hover:text-white rounded-tl-lg rounded-br-lg p-2   " href="" >
        {{Str::ucfirst(__('categories'))}}
    </a>
    <a class="shadow shadow-inherit bg-slate-950 hover:bg-stone-700 hover:text-white rounded-tl-lg rounded-br-lg p-2 " href="" >
        {{ Str::ucfirst(__('articles'))  }}
    </a>
    <a class="shadow shadow-inherit bg-slate-950 hover:bg-stone-700 hover:text-white rounded-tl-lg rounded-br-lg p-2   " href="{{ route('usuarios.index') }}" >
        {{Str::ucfirst(__('users'))}}
    </a>
    <a class="shadow shadow-inherit bg-slate-950 hover:bg-stone-700 hover:text-white rounded-tl-lg rounded-br-lg p-2   " href="{{ route('panel.index') }}" >
        {{Str::ucfirst(__('panel'))}}
    </a>
</nav>

resources/views/inc/panel/nav-perfil.blade.php
<div
    x-data="{
        open: false,
        toggle() {
            if (this.open) {
                return this.close()
            }

            this.$refs.button.focus()

            this.open = true
        },
        close(focusAfter) {
            if (! this.open) return

            this.open = false

            focusAfter && focusAfter.focus()
        }
    }"
    x-on:keydown.escape.prevent.stop="close($refs.button)"
    x-on:focusin.window="! $refs.panel.contains($event.target) && close()"
    x-id="['dropdown-button']"
    class="relative"
    >
        <!-- Button -->
        <button
            x-ref="button"
            x-on:click="toggle()"
            :aria-expanded="open"
            :aria-controls="$id('dropdown-button')"
            type="button"
            class="flex items-center text-2xl w-full gap-2 bg-slate-950 px-5 py-2.5 rounded-tl-lg rounded-br-lg"
        >
        @if (auth()->user()->image)
            <img src="{{ Storage::url(auth()->user()->image()->first()->url) }}" alt="" class=" border-2 border-red-950 w-10 h-10  rounded-full shadow shadow-black mr-3">
        @else
            <img src="{{ Vite::img('logo.png') }}" alt="" class=" border-2 border-red-950 w-10 h-10  rounded-full shadow shadow-black mr-3 bg-cover">
        @endif
            <span class="mr-0">@ {{Str::lower(auth()->user()->username)}}</span>

            <!-- Heroicon: chevron-down -->
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
        </button>

        <!-- Panel -->
        <div
            x-ref="panel"
            x-show="open"
            x-transition.origin.top.left
            x-on:click.outside="close($refs.button)"
            :id="$id('dropdown-button')"
            style="display: none;"
            class="absolute left-0 mt-1 w-40 text-xl rounded-md shadow shadow-black  bg-zinc-900 "
        >
            {{-- <a href="{{ route('usuario.profile') }}" class="flex items-center gap-2 w-full first-of-type:rounded-t-md last-of-type:rounded-b-md px-4 py-2.5 text-left  hover:bg-black disabled:text-gray-500">
                {{ Str::ucfirst(__('profile'))}}
            </a> --}}
            <form method="POST" action="{{ route('logout') }}">
                @csrf

                <a href="{{ route('logout') }}"
                   class=" flex items-center gap-2 w-full first-of-type:rounded-t-md last-of-type:rounded-b-md px-4 py-2.5 text-left  hover:bg-black disabled:text-gray-500"
                                     onclick="event.preventDefault();
                                                this.closest('form').submit();">
                    {{Str::ucfirst(__('logout')) }}
                </a>
            </form>
        </div>
</div>

resources/views/inc/panel/nav-side.blade.php
{{-- <div class="min-h-screen bg-gray-100 ">
</div> --}}
<div class="bg-black min-h-screen w-[3.33rem] overflow-hidden shadow shadow-slate-950 hover:w-56 lg:hidden grid col-span-1 z-50">
    <div class="flex h-screen flex-col justify-between pt-2 pb-6">
        <div>
            <div class="w-max p-2.5">
                <img src="https://tailus.io/images/logo.svg" class="w-32" alt="">
            </div>
            <ul class="mt-6 space-y-2 tracking-wide">
                <li class="min-w-max">
                    <a href="#" aria-label="dashboard"
                        class="relative flex items-center space-x-4 bg-gradient-to-r from-sky-600 to-cyan-400 px-4 py-3 text-white">
                        <svg class="-ml-1 h-6 w-6" viewBox="0 0 24 24" fill="none">
                            <path
                                d="M6 8a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8ZM6 15a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2v-1Z"
                                class="fill-current text-cyan-400 dark:fill-slate-600"></path>
                            <path d="M13 8a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2V8Z"
                                class="fill-current text-cyan-200 group-hover:text-cyan-300"></path>
                            <path d="M13 15a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-1Z"
                                class="fill-current group-hover:text-sky-300"></path>
                        </svg>
                        <span class="-mr-1 font-medium">Dashboard</span>
                    </a>
                </li>
                <li class="min-w-max">
                    <a href="#" class="bg group flex items-center space-x-4 rounded-full px-4 py-3 text-gray-600">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                            fill="currentColor">
                            <path class="fill-current text-gray-300 group-hover:text-cyan-300" fill-rule="evenodd"
                                d="M2 6a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1H8a3 3 0 00-3 3v1.5a1.5 1.5 0 01-3 0V6z"
                                clip-rule="evenodd" />
                            <path class="fill-current text-gray-600 group-hover:text-cyan-600"
                                d="M6 12a2 2 0 012-2h8a2 2 0 012 2v2a2 2 0 01-2 2H2h2a2 2 0 002-2v-2z" />
                        </svg>
                        <span class="group-hover:text-gray-700">Categories</span>
                    </a>
                </li>
                <li class="min-w-max">
                    <a href="#" class="group flex items-center space-x-4 rounded-md px-4 py-3 text-gray-600">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                            fill="currentColor">
                            <path class="fill-current text-gray-600 group-hover:text-cyan-600" fill-rule="evenodd"
                                d="M2 5a2 2 0 012-2h8a2 2 0 012 2v10a2 2 0 002 2H4a2 2 0 01-2-2V5zm3 1h6v4H5V6zm6 6H5v2h6v-2z"
                                clip-rule="evenodd" />
                            <path class="fill-current text-gray-300 group-hover:text-cyan-300"
                                d="M15 7h1a2 2 0 012 2v5.5a1.5 1.5 0 01-3 0V7z" />
                        </svg>
                        <span class="group-hover:text-gray-700">Reports</span>
                    </a>
                </li>
                <li class="min-w-max">
                    <a href="#" class="group flex items-center space-x-4 rounded-md px-4 py-3 text-gray-600">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                            fill="currentColor">
                            <path class="fill-current text-gray-600 group-hover:text-cyan-600"
                                d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                            <path class="fill-current text-gray-300 group-hover:text-cyan-300"
                                d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                        </svg>
                        <span class="group-hover:text-gray-700">Other data</span>
                    </a>
                </li>
                <li class="min-w-max">
                    <a href="#" class="group flex items-center space-x-4 rounded-md px-4 py-3 text-gray-600">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                            fill="currentColor">
                            <path class="fill-current text-gray-300 group-hover:text-cyan-300"
                                d="M4 4a2 2 0 00-2 2v1h16V6a2 2 0 00-2-2H4z" />
                            <path class="fill-current text-gray-600 group-hover:text-cyan-600" fill-rule="evenodd"
                                d="M18 9H2v5a2 2 0 002 2h12a2 2 0 002-2V9zM4 13a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5-1a1 1 0 100 2h1a1 1 0 100-2H9z"
                                clip-rule="evenodd" />
                        </svg>
                        <span class="group-hover:text-gray-700">Finance</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="w-max -mb-3">
            <a href="#" class="group flex items-center space-x-4 rounded-md px-4 py-3 text-gray-600">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 group-hover:fill-cyan-600"
                    viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd"
                        d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                        clip-rule="evenodd" />
                </svg>
                <span class="group-hover:text-gray-700">Settings</span>
            </a>
        </div>
    </div>
</div>