routes/web.php
<?php

use App\Http\Livewire\Access\RegLog;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Panel\Users\Users;
use App\Http\Livewire\Panel\PanelControl;
use App\Http\Controllers\VerifyUserController;
use App\Http\Livewire\Panel\Users\UserRegiEdit;

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/', PanelControl::class)->name('user');

Route::get('reg-log', RegLog::class)->name('login');
Route::post('reg-log', RegLog::class)->name('logout');

Route::get('account/verify/{token}', VerifyUserController::class)->name('verify');

Route::group(['middleware' => ['auth', 'user-veri-email'], 'prefix' => 'panel'], function(){

    Route::group(['prefix' => '', 'as' => 'panel.'], function(){

        // Panel
        Route::get('', PanelControl::class)->name('index');

    });

    Route::group(['prefix' => 'usuarios', 'as' => 'usuarios.'], function(){

        Route::get('', Users::class)->name('index');
        // Route::get('crear', UserForm::class)->name('create');
        // Route::get('{user}', UserShow::class)->name('show');

        // Route::get('{user}/borrar', Users::class)->name('delete');
        // Route::get('{user}/perfil', UserProfile::class)->name('details');
        // Route::view('/perfil/user', 'partials.panel.perfil')->name('profile');
    });

    Route::group(['prefix' => 'usuario', 'as' => 'usuario.'], function(){

        Route::get('crear', UserRegiEdit::class)->name('create');
        Route::get('{user}/editar', UserRegiEdit::class)->name('editar');

        // Route::get('{user}/borrar', Users::class)->name('delete');
        // Route::get('{user}/perfil', UserProfile::class)->name('details');
        // Route::view('/perfil/user', 'partials.panel.perfil')->name('profile');
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Traits\HasSlug;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, HasSlug;

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function articulos(): HasMany
    {
        return $this->hasMany(Articulo::class);
    }

    public function image(): MorphOne
    {
        return $this->morphOne(Img::class, 'imageable');
    }
}

app/Http/Livewire/Panel/PanelControl.php
<?php

namespace App\Http\Livewire\Panel;

use Livewire\Component;

class PanelControl extends Component
{
    public function render()
    {
        return view('livewire.panel.panel-control')
        ->layout('layouts.app-panel', ['title' => 'Control Panel']);
    }
}

app/Http/Livewire/Panel/Users/UserPass.php
<?php

namespace App\Http\Livewire\Panel\Users;

use App\Models\User;
use Livewire\Component;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserPass extends Component
{
    // public User $user;
    public $user, $current_password, $new_password, $confirm_password;


    // public function mount(User $user)
    // {
    //     $this->user = $user;    
    // }

    public function render()
    {
        return view('livewire.panel.users.user-pass')
        ->layout('layouts.app-panel', ['title' => 'Usuario contraseña']);
    }

    public function changepass()
    {
        $this->validate([
            'current_password'  => [
                'required',
                function ($value, $error)
                {
                    if (!Hash::check($value, User::find($this->user->id)->password)) {
                        return $error(__('the current password is incorrect'));
                    }
                },
            ],
            'new_password'     => 'required|min:3',
            'confirm_password' => 'same:new_password',
        
        ],[
            'current_password.required'  => __('enter your current password.'),
            'new_password.required'      => __('enter your new password.'),
            'confirm_password.same'      => __('confirme new password, must be equals to the new password'),
        ]);

        $query = User::find(auth('web')->id())->update([
            'password' => bcrypt($this->new_password)
        ]);

        if ($query) {
            session()->flash('msg', __('contra cambiada correctamente.'));
            $this->redirectRoute('usuarios.index');
            $this->current_password = $this->new_password = $this->confirm_password = null;
        } else {
            session()->flash('msg', __('error con las contraseñas.'));
        }
        
        // dd('los passworeds');
    }

}

app/Http/Livewire/Panel/Users/UserRegiEdit.php
<?php

namespace App\Http\Livewire\Panel\Users;

use App\Models\Img;
use App\Models\User;
use App\Traits\hasUpload;
use Livewire\Component;
use Livewire\WithFileUploads;
use Illuminate\Validation\Rule;

class UserRegiEdit extends Component
{
    use WithFileUploads, hasUpload;

    public User $user;
    public $photo;
    public $password;

    protected function rules(){
        return [
            'user.name' => 'required|min:3|string',
            'user.username' => 'nullable|min:3',
            'user.slug' => [
                'nullable',
                'alpha_dash',
                Rule::unique('users', 'slug')->ignore($this->user)
            ],
            'user.email' => [
                'required',
                Rule::unique('users', 'email')->ignore($this->user)
            ],
            'user.bio' => 'nullable|min:3',
            'photo' => [
                $this->user->photo ? '' : '',
                'nullable',
                'image',
                'max:2048',
                // Rule::exists('users', 'photo')->ignore($this->user)
            ],
            // 'photo' => 'nullable|exists:users,photo,'.$this->user->photo,
            'password' => [
                'required',
                'min:3',
                Rule::unique('users', 'password')->ignore($this->user->id)
            ]
        ];
    }

    public function mount(User $user, Img $photo){
        $this->user = $user;
        $this->photo = $photo;
        $this->password = $user->password;
    }

    public function updated($propertyName){
        $this->validateOnly($propertyName);
    }

    public function regedit(){
        $this->validate();

        $this->user->password = bcrypt($this->password);
        $this->user->save();

        if ($this->photo) {
            $this->photo = $this->uploadImage($this->user);
        }

        session()->flash('msg', __('user successfully created or edited.'));
        $this->redirectRoute('usuarios.index');
    }

    public function render(){
        return view('livewire.panel.users.user-regi-edit')
            ->layout('layouts.app-panel', ['title' => 'Crear Usuario']);
    }
}

app/Http/Livewire/Panel/Users/Users.php
<?php

namespace App\Http\Livewire\Panel\Users;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Users extends Component
{
    use WithPagination;

    public $search = '';

    public function render()
    {
        return view('livewire.panel.users.users', [
            'users' => User::where('name', 'like', "%{$this->search}%")->latest()->get()
        ])
        ->layout('layouts.app-panel', ['title' => 'Panel Usuarios']);
    }
}

resources/views/livewire/panel/users/user-pass.blade.php
<div>
    <form wire:submit.prevent="changepass" class="w-full p-3 mx-auto text-xl text-white rounded-tl-lg rounded-br-lg shadow shadow-slate-900 ">
        <label class="w-full">
            <span class="">{{Str::ucfirst(__('password'))}} actual</span>
            <input wire:model.defer="current_password" type="password"  class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3 placeholder:text-white " autofocus placeholder="***********" />
            @error("current_password")
                <span class="text-red-300">{{ $message }}</span>   
            @enderror
        </label>
        <div class="flex flex-col justify-center lg:flex-row lg:space-x-3">
            <label class="w-full">
                <span class="">Nueva {{Str::ucfirst(__('password'))}}</span>
                <input wire:model.defer="new_password" type="password"  class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3 placeholder:text-white " placeholder="********" />
                @error("new_password")
                    <span class="text-red-300">{{ $message }}</span>   
                @enderror
            </label>
            <label class="w-full">
                <span class="">Repetir {{Str::ucfirst(__('password'))}}</span>
                <input wire:model.defer="confirm_password" type="password"  class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3 placeholder:text-white " placeholder="************" />
                @error("confirm_password")
                    <span class="text-red-300 ">{{ $message }}</span>   
                @enderror
            </label>
        </div>
        <div class="flex items-center justify-center mt-3 space-x-3 ">
            <input type="submit" class="block w-full p-3 italic text-black bg-green-300 rounded-tl-lg rounded-br-lg shadow cursor-pointer shadow-green-800 " value="{{__('Changed password')}}" />
            <a href="{{ route('user.index') }}"  class="flex justify-center w-full p-3 italic text-black bg-green-300 rounded-tl-lg rounded-br-lg shadow cursor-pointer shadow-green-800" >
                {{__('Cancelar')}}
            </a>
        </div>
    </form>
</div>

resources/views/livewire/panel/users/user-regi-edit.blade.php
<div>
    <h2 class="flex justify-center w-full p-2 m-2 mx-auto text-white rounded shadow bg-emerald-900 shadow-inherit">
        {{Str::ucfirst(__('created user'))}}
    </h2>

    <form wire:submit.prevent="regedit" class=" w-full p-3 text-xl bg-[#3d3232] shadow  shadow-slate-900 rounded-tl-lg rounded-br-lg text-white">
        <div class="flex flex-col lg:flex-row lg:space-x-3">
            <label class="block w-full">
                <span class="mt-4 ">{{Str::ucfirst(__('name'))}}</span>
                <input wire:model.defer="user.name" type="text"  class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3 placeholder:text-red-400  " autofocus placeholder="name" />
                @error("user.name")
                    <span class="text-red-300">{{ $message }}</span>
                @enderror
            </label>
            <label class="block w-full">
                <span class="mt-4 ">{{Str::ucfirst(__('username'))}}</span>
                <input wire:model.defer="user.username" type="text"  class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3 placeholder:text-red-400  " placeholder="usuario" />
                @error("user.username")
                    <span class="text-red-300">{{ $message }}</span>
                @enderror
            </label>
        </div>
        <div class="flex flex-col lg:flex-row lg:space-x-3">
            <label class="block w-full">
                <span class="mt-4 ">{{Str::ucfirst(__('email'))}}</span>
                <input wire:model.defer="user.email" type="email"  class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3  placeholder:text-red-400 h-[3.95rem] " placeholder="correo" />
                @error("user.email")
                    <span class="text-red-300">{{ $message }}</span>
                @enderror
            </label>
            <label class="block w-full">
                <span class="mt-4 ">{{Str::ucfirst(__('bio'))}}</span>
                <textarea  rows="1" wire:model.defer="user.bio" class="mt-0 block w-full px-0.5 border-0 h-[3.95rem] border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-white text-xl italic mb-3 placeholder:text-red-400 " placeholder="biografía"></textarea>
                @error("user.bio")
                    <span class="text-red-300">{{ $message }}</span>
                @enderror
            </label>
        </div>

        {{-- @include('inc.panel.img') --}}
        <label class="relative flex items-center justify-center w-auto p-3 mx-auto my-5 border border-dashed rounded-tl-lg rounded-br-lg shadow h-96 shadow-inherit bg-slate-700">
            @if ($photo instanceof Livewire\TemporaryUploadedFile)
                <span wire:click="$set('photo')" class="absolute p-3 bg-orange-600 rounded-tl-lg rounded-br-lg shadow cursor-pointer bottom-2 right-2 shadow-inherit">
                    {{Str::ucfirst(__('change photo'))}}
                </span>
                <img class="w-full h-full bg-cover " src="{{ $photo->temporaryUrl() }}" alt="">
            @elseif ($user->image()->exists())
                <img src="{{ Storage::url(optional($user->image()->first())->url) }}" alt=""  class="h-full bg-cover ">
                <span class="absolute p-3 bg-orange-600 rounded-tl-lg rounded-br-lg shadow cursor-pointer bottom-2 right-2 shadow-inherit">
                {{Str::ucfirst(__('change photo'))}}
                </span>
                <input wire:model="photo" class="my-5 text-xl text-white border border-gray-300 cursor-pointer sr-only bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" type="file">
                @error("photo")
                <span class="absolute p-2 text-xl text-white top-2 bg-slate-950">{{ $message }}</span>
                @enderror
            @else
                <span class="p-3 bg-orange-600 rounded-tl-lg rounded-br-lg shadow cursor-pointer shadow-inherit">
                {{Str::ucfirst(__('select profile picture'))}}
                </span>
                <input wire:model="photo" class="my-5 text-xl text-white border border-gray-300 cursor-pointer sr-only bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" type="file">
                @error("photo")
                <span class="absolute p-2 text-xl text-white top-2 bg-slate-950">{{ $message }}</span>
                @enderror
            @endif

        </label>


        <label class="block mt-4">
            <span class="">{{Str::ucfirst(__('password'))  }}</span>
            <input wire:model.defer="password" type="password" class="mt-0 block w-full px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-xl italic mb-3 placeholder:text-red-400" />
            @error('password')
                <span class="text-red-300 ">{{ $message }}</span>
            @enderror
        </label>
        <div class="flex space-x-3 ">
            <input type="submit" class="block w-full p-3 mt-4 italic text-yellow-300 capitalize rounded-tl-lg rounded-br-lg shadow cursor-pointer bg-indigo-950 shadow-inherit " value="{{Str::ucfirst(__('create or edit user'))}}" />
            <a href="{{ route('usuarios.index') }}" class="flex justify-center w-full p-3 mt-4 italic text-yellow-300 capitalize rounded-tl-lg rounded-br-lg shadow cursor-pointer bg-indigo-950 shadow-inherit ">
                Cancelar
            </a>
        </div>
    </form>
</div>

resources/views/livewire/panel/users/users.blade.php
<div>
    <div class="flex justify-center gap-2 p-1 m-2 bg-orange-800 rounded-md shadow shadow-current">
        <a class="block w-2/5 p-1 my-3 italic text-center text-white bg-pink-900 rounded-tl-lg rounded-br-lg shadow cursor-pointer shadow-current" href="{{ route('usuario.create') }}">
            {{Str::ucfirst(__('created user'))}}
        </a>
        <input type="search" class=" text-white mt-0 w-full  px-0.5 border-0 border-b-2 border-b-green-200 focus:ring-0 focus:border-yellow-300 appearance-none bg-none bg-transparent text-xl italic mb-3 placeholder:text-white" wire:model="search"  placeholder="Buscar ... ">
    </div>
    @if (session('msg'))
        <div class="flex justify-center p-2 m-2 text-white shadow bg-cyan-700 shadow-inherit">
            {{ Str::ucfirst(session('msg')) }}
        </div>
    @endif
    @forelse ($users as $user)
        <div class="flex flex-col p-3 mt-4 divide-y shadow shadow-black bg-zinc-900 ">
            <div class="flex flex-col items-center justify-center p-2 lg:flex-row lg:justify-start lg:space-x-3">
                <span class="text-xl text-white">Nombre(s) :</span>
                <li class="text-yellow-300 list-none ">
                    {{ Str::ucfirst(__($user->name))  }}
                </li>
            </div>
            <div class="flex flex-col items-center justify-center p-2 lg:flex-row lg:justify-start lg:space-x-3">
                <span class="text-xl text-white">Usuario :</span>
                <li class="text-yellow-300 list-none ">
                    @if ($user->username)
                        {{ __($user->username) }}
                    @else
                    <p class="flex justify-center text-white ">
                        {{ Str::ucfirst(__('no tiene url '))}}
                        {{ __('whoops!') }}
                    </p>
                    @endif
                </li>
            </div>
            <div class="flex flex-col items-center justify-center p-2 lg:flex-row lg:justify-start lg:space-x-3">
                <span class="text-xl text-white">Url amigable :</span>
                <li class="text-yellow-300 list-none ">
                    @if ($user->slug)
                        {{ Str::lower(__($user->slug))}}
                    @else
                    <p class="flex justify-center text-white ">
                        {{ Str::ucfirst(__('no tiene url '))}}
                        {{ __('whoops!') }}
                    </p>
                    @endif
                </li>
            </div>
            <div class="flex flex-col items-center justify-center p-2 lg:flex-row lg:justify-start lg:space-x-3">
                <span class="text-xl text-white">Imagen :</span>
                <li class="text-yellow-300 list-none ">
                    @if ($user->image)
                        <img src="{{ Storage::url($user->image()->first()->url) }}" alt=""  class="w-8 h-8 rounded-full ">
                    @else
                    <p class="flex justify-center text-white ">
                        {{ Str::ucfirst(__('no tiene imagen '))}}
                        {{ __('whoops!') }}
                    </p>
                    @endif
                </li>
            </div>
            <div class="flex flex-col items-center justify-center p-2 lg:flex-row lg:justify-start lg:space-x-3">
                <span class="text-xl text-white">Correo electrónico :</span>
                <li class="text-yellow-300 list-none ">
                    <a class="hover:underline" href="mailto:{{ __($user->email) }}">{{ __($user->email) }}</a>
                </li>
            </div>
            <div class="flex flex-col items-center justify-center p-2 lg:flex-row lg:justify-start lg:space-x-3">
                <span class="text-xl text-white">Biografia :</span>
                <li class="text-yellow-300 list-none ">
                    @if ($user->bio)
                        {{ Str::ucfirst($user->bio) }}
                    @else
                    <p class="flex justify-center text-white ">
                        {{ Str::ucfirst(__('no tiene biografia '))}}
                        {{ __('whoops!') }}
                    </p>
                    @endif
                </li>
            </div>
            <div class="flex justify-center p-3 space-x-3 text-yellow-300 lg:justify-start">

                <a href="{{ route('usuario.editar', $user) }}" class="p-2 rounded-tl-lg rounded-br-lg shadow shadow-black bg-rose-950" >
                    {{ Str::ucfirst(__('edit'))}}
                </a>
                <a href="" class="p-2 rounded-tl-lg rounded-br-lg shadow shadow-black bg-rose-950" >
                    {{ Str::ucfirst(__('delete'))}}
                </a>
            </div>
        </div>
    @empty
        <p class="flex justify-center p-2 m-2 text-white bg-black shadow shadow-inherit">

            {{ Str::ucfirst(__('no users registered.'))}}
            {{ __('whoops!') }}
        </p>
    @endforelse
</div>